export const CREATE_POST='CREATE_POST'
export const CREATE_POST_SUCCESS='CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR='CREATE_POST_ERROR'

export const GET_ALL_POST='GET_ALL_POST'
export const GET_ALL_POST_SUCCESS='GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_ERROR='GET_ALL_POST_ERROR'

export const UPDATE_ONE_POST='UPDATE_ONE_POST'
export const UPDATE_ONE_POST_SUCCESS='UPDATE_ONE_POST_SUCCESS'
export const UPDATE_ONE_POST_ERROR='UPDATE_ONE_POST_ERROR'

export const DELETE_ONE_POST='DELETE_ONE_POST'
export const DELETE_ONE_POST_SUCCESS='DELETE_ONE_POST_SUCCESS'
export const DELETE_ONE_POST_ERROR='DELETE_ONE_POST_ERROR'

export const LIKE_ONE_POST='LIKE_ONE_POST'
export const LIKE_ONE_POST_SUCCESS='LIKE_ONE_POST_SUCCESS'
export const LIKE_ONE_POST_ERROR='LIKE_ONE_POST_ERROR'

export const DISLIKE_ONE_POST='DISLIKE_ONE_POST'
export const DISLIKE_ONE_POST_SUCCESS='DISLIKE_ONE_POST_SUCCESS'
export const DISLIKE_ONE_POST_ERROR='DISLIKE_ONE_POST_ERROR'

