export const SIGNUP_USER='SIGNUP_USER'
export const SIGNUP_USER_SUCCESS='SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR='SIGNUP_USER_ERROR'

export const SET_CURRENT_USER='SET_CURRENT_USER'
export const LOG_OUT='LOG_OUT'

export const SIGNIN_USER='SIGNIN_USER'
export const SIGNIN_USER_SUCCESS='SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_ERROR='SIGNIN_USER_ERROR'

export const UPDATE_USER='UPDATE_USER'
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR='UPDATE_USER_ERROR'

export const DELETE_USER='DELETE_USER'
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR='DELETE_USER_ERROR'
