export const SIGNUP_USER='SIGNUP_USER'
export const SIGNUP_USER_SUCCESS='SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR='SIGNUP_USER_ERROR'
export const SET_CURRENT_USER='SET_CURRENT_USER'
export const LOG_OUT='LOG_OUT'

export const SIGNIN_USER='SIGNIN_USER'
export const SIGNIN_USER_SUCCESS='SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_ERROR='SIGNIN_USER_ERROR'
